apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-core-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-core-service
  template:
    metadata:
      labels:
        app: shop-core-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: shop-core-service
          image: geizerde/shop-core:v1.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: shop-config
            - secretRef:
                name: db-credentials
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 15
            failureThreshold: 2

          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"
