apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-total-cost-of-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-total-cost-of-order-service
  template:
    metadata:
      labels:
        app: shop-total-cost-of-order-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: shop-total-cost-of-order-service
          image: geizerde/shop-total-cost-of-order:v1.4.0-retry
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: shop-config
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"